name: "Annual Reports (PDF)"
type: pdf
seed_url: "https://www.intc.com/financials/annual-reports"

# Crawler settings
url_patterns: ['\\.pdf$']
max_depth: 1

# Parser settings (for PDFScraper + AIParser)
# The PDF scraper extracts the text, which is then passed to a parser.
parser_type: ai
parser_config:
  model: "deepseek-coder:1.3b"
  prompt_template: "From the following text of an annual report, extract the 'Net Revenue', 'Gross Margin', and 'Net Income'. Return as a JSON object. Text: {text}"
  fields: ["Net Revenue", "Gross Margin", "Net Income"]

