name: "GitHub API (JSON)"
type: api
seed_url: "https://api.github.com/users/google/repos"

# Scraper settings (for APIScraper)
headers:
  Accept: "application/vnd.github.v3+json"

# Parser settings
parser_type: json
parser_config:
  container: "$[*]"
  fields:
    repo_name: "$.name"
    full_name: "$.full_name"
    url: "$.html_url"
    stars: "$.stargazers_count"
    language: "$.language"
