name: "OpenWeatherMap API"
type: api
seed_url: "https://api.openweathermap.org/data/2.5/weather?q=London&appid=YOUR_API_KEY" # Placeholder API Key

# Scraper settings
headers:
  Accept: "application/json"

# Parser settings
parser_type: json
parser_config:
  container: "$" # The root of the JSON response is the container
  fields:
    city: "$.name"
    temperature: "$.main.temp"
    feels_like: "$.main.feels_like"
    humidity: "$.main.humidity"
    weather_description: "$.weather[0].description"
