groups:
  - name: general.rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  - name: api.rules
    rules:
      - alert: ApiDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API instance {{ $labels.instance }} down"
          description: "FastAPI application instance {{ $labels.instance }} is down."

      - alert: ApiHighErrorRate
        expr: sum(rate(api_requests_total{status_code=~"5..", job="api"}[5m])) by (instance) / sum(rate(api_requests_total{job="api"}[5m])) by (instance) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API instance {{ $labels.instance }} has high error rate"
          description: "FastAPI application instance {{ $labels.instance }} has an error rate above 5% for the last 5 minutes."

  - name: system.rules
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage on {{ $labels.instance }} is above 80% for the last 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage on {{ $labels.instance }} is above 80% for the last 5 minutes."

  - name: scraping.rules
    rules:
      - alert: ScraperFailed
        expr: sum(rate(scraper_requests_total{status="failed"}[5m])) by (instance, site) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Scraping job failed for site {{ $labels.site }}"
          description: "Scraping job for site {{ $labels.site }} on instance {{ $labels.instance }} has failed."
